### ISSUE TITLE
Videoscrub on Smaller Mac

### ISSUE THREAD

**Issue by URBabylab** [SeedlingsBabylab/videoscrub#3]
Videoscrub doesn't work on the smaller Mac. Comes up with this error: 
temp/audio_scrub_output.mp4: No such file or directory

**Comment by URBabylab** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1410, in **call**
    return self.func(*args)
  File "videoscrub-gui.py", line 117, in scrub
    self.scrub_video()
  File "videoscrub-gui.py", line 214, in scrub_video
    os.remove("temp/audio_scrub_output.mp4")
OSError: [Errno 2] No such file or directory: 'temp/audio_scrub_output.mp4'
